- platform: mqtt
  name: "Shutter Office LED"
  command_topic: "cmnd/shutter_office/shutterposition"
  payload_on: "7,1"
  payload_off: "7,0"
  qos: 2
  retain: false

- platform: mqtt
  name: "Shutter Dinner LED"
  command_topic: "cmnd/shutter_dinner/shutterposition"
  payload_on: "7,1"
  payload_off: "7,0"
  qos: 2
  retain: false

- platform: mqtt
  name: "Shutter Sleep LED"
  command_topic: "cmnd/shutter_sleep/shutterposition"
  payload_on: "7,1"
  payload_off: "7,0"
  qos: 2
  retain: false        

- platform: mqtt
  name: "Shutter Room LED"
  command_topic: "cmnd/shutter_room/shutterposition"
  payload_on: "7,1"
  payload_off: "7,0"
  qos: 2
  retain: false    